/* GENERATED — do not hand-edit.

   The real Blurb price matrix, extracted from the pricingData payload
   embedded in https://www.blurb.com/pricing on 2026-08-18.

   Prices are a LOOKUP, not base-plus-deltas: every size + paper + cover
   combination carries its own price, and not every combination exists.
   Regenerate by re-parsing that page rather than editing values here.
*/
export const PRICING = {
 "additionalPages": {
  "large_format_landscape_premium_matte_layflat_paper": 1.5,
  "large_format_landscape_premium_paper": 0.84,
  "large_format_landscape_premium_paper_lustre": 0.84,
  "large_format_landscape_pro_medium_gloss_paper": 0.99,
  "large_format_landscape_pro_photo_layflat_paper": 4.5,
  "large_format_landscape_pro_uncoated_layflat_paper": 4.5,
  "large_format_landscape_pro_uncoated_paper": 0.92,
  "large_format_landscape_standard_layflat_paper": 2.52,
  "large_format_landscape_standard_paper": 0.7,
  "large_square_premium_matte_layflat_paper": 1.5,
  "large_square_premium_paper": 0.84,
  "large_square_premium_paper_lustre": 0.84,
  "large_square_pro_medium_gloss_paper": 0.99,
  "large_square_pro_photo_layflat_paper": 4.5,
  "large_square_pro_uncoated_layflat_paper": 4.5,
  "large_square_pro_uncoated_paper": 0.92,
  "large_square_standard_layflat_paper": 2.52,
  "large_square_standard_paper": 0.7,
  "large_text_economy_trade_bw_cream_matte_paper": 0.02,
  "large_text_economy_trade_bw_matte_paper": 0.02,
  "large_text_economy_trade_matte_paper": 0.06,
  "large_text_standard_trade_bw_matte_paper": 0.04,
  "large_text_standard_trade_matte_paper": 0.16,
  "magazine_magazine_paper": 0.15,
  "magazine_velvet_paper": 0.2,
  "pocket_text_economy_trade_bw_cream_matte_paper": 0.02,
  "pocket_text_economy_trade_bw_matte_paper": 0.02,
  "pocket_text_economy_trade_matte_paper": 0.06,
  "pocket_text_standard_trade_bw_matte_paper": 0.04,
  "pocket_text_standard_trade_matte_paper": 0.16,
  "small_square_premium_matte_layflat_paper": 0.0,
  "small_square_premium_paper": 0.0,
  "small_square_premium_paper_lustre": 0.31,
  "small_square_pro_medium_gloss_paper": 0.0,
  "small_square_pro_photo_layflat_paper": 0.0,
  "small_square_pro_uncoated_layflat_paper": 0.0,
  "small_square_pro_uncoated_paper": 0.0,
  "small_square_standard_layflat_paper": 0.0,
  "small_square_standard_paper": 0.0,
  "square_premium_matte_layflat_paper": 1.1,
  "square_premium_paper": 0.4,
  "square_premium_paper_lustre": 0.4,
  "square_pro_medium_gloss_paper": 0.55,
  "square_pro_photo_layflat_paper": 3.5,
  "square_pro_uncoated_layflat_paper": 3.5,
  "square_pro_uncoated_paper": 0.48,
  "square_standard_layflat_paper": 1.68,
  "square_standard_paper": 0.26,
  "standard_landscape_premium_matte_layflat_paper": 1.1,
  "standard_landscape_premium_paper": 0.45,
  "standard_landscape_premium_paper_lustre": 0.45,
  "standard_landscape_pro_medium_gloss_paper": 0.61,
  "standard_landscape_pro_photo_layflat_paper": 3.5,
  "standard_landscape_pro_uncoated_layflat_paper": 3.5,
  "standard_landscape_pro_uncoated_paper": 0.54,
  "standard_landscape_standard_layflat_paper": 1.85,
  "standard_landscape_standard_paper": 0.33,
  "standard_portrait_premium_matte_layflat_paper": 1.1,
  "standard_portrait_premium_paper": 0.45,
  "standard_portrait_premium_paper_lustre": 0.45,
  "standard_portrait_pro_medium_gloss_paper": 0.61,
  "standard_portrait_pro_photo_layflat_paper": 3.5,
  "standard_portrait_pro_uncoated_layflat_paper": 3.5,
  "standard_portrait_pro_uncoated_paper": 0.54,
  "standard_portrait_standard_layflat_paper": 1.85,
  "standard_portrait_standard_paper": 0.33,
  "standard_portrait_true8x10_economy_trade_bw_cream_matte_paper": 0.03,
  "standard_portrait_true8x10_economy_trade_bw_matte_paper": 0.03,
  "standard_portrait_true8x10_economy_trade_matte_paper": 0.07,
  "standard_portrait_true8x10_premium_matte_layflat_paper": 1.1,
  "standard_portrait_true8x10_premium_paper": 0.45,
  "standard_portrait_true8x10_premium_paper_lustre": 0.45,
  "standard_portrait_true8x10_pro_medium_gloss_paper": 0.61,
  "standard_portrait_true8x10_pro_photo_layflat_paper": 3.5,
  "standard_portrait_true8x10_pro_uncoated_layflat_paper": 3.5,
  "standard_portrait_true8x10_pro_uncoated_paper": 0.54,
  "standard_portrait_true8x10_standard_layflat_paper": 1.85,
  "standard_portrait_true8x10_standard_paper": 0.33,
  "standard_portrait_true8x10_standard_trade_bw_matte_paper": 0.05,
  "standard_portrait_true8x10_standard_trade_matte_paper": 0.17
 },
 "ebooks": {
  "fixed_layout_ebook": 9.99,
  "pdf": 4.99
 },
 "families": {
  "notebooks": {
   "dustjacket": {
    "large_text_standard_trade_matte_paper": 29.67,
    "pocket_text_standard_trade_matte_paper": 28.67
   },
   "imagewrap": {
    "large_text_standard_trade_matte_paper": 28.67,
    "pocket_text_standard_trade_matte_paper": 27.67,
    "standard_portrait_true8x10_standard_trade_matte_paper": 31.15
   },
   "softcover": {
    "large_text_standard_trade_matte_paper": 15.67,
    "pocket_text_standard_trade_matte_paper": 14.67,
    "standard_portrait_true8x10_standard_trade_matte_paper": 17.15
   },
   "softcover_wireo": {
    "large_text_standard_trade_matte_paper": 15.67,
    "pocket_text_standard_trade_matte_paper": 14.67,
    "standard_portrait_true8x10_standard_trade_matte_paper": 17.15
   }
  },
  "photo_books": {
   "dustjacket": {
    "large_format_landscape_premium_paper": 74.0,
    "large_format_landscape_premium_paper_lustre": 74.0,
    "large_format_landscape_pro_medium_gloss_paper": 95.0,
    "large_format_landscape_pro_uncoated_paper": 88.0,
    "large_format_landscape_standard_paper": 68.0,
    "large_square_premium_paper": 70.0,
    "large_square_premium_paper_lustre": 70.0,
    "large_square_pro_medium_gloss_paper": 94.0,
    "large_square_pro_uncoated_paper": 85.0,
    "large_square_standard_paper": 64.0,
    "square_premium_paper": 36.0,
    "square_premium_paper_lustre": 36.0,
    "square_pro_medium_gloss_paper": 48.0,
    "square_pro_uncoated_paper": 42.0,
    "square_standard_paper": 32.0,
    "standard_landscape_premium_paper": 42.0,
    "standard_landscape_premium_paper_lustre": 42.0,
    "standard_landscape_pro_medium_gloss_paper": 58.0,
    "standard_landscape_pro_uncoated_paper": 51.0,
    "standard_landscape_standard_paper": 38.0,
    "standard_portrait_premium_paper": 42.0,
    "standard_portrait_premium_paper_lustre": 42.0,
    "standard_portrait_pro_medium_gloss_paper": 58.0,
    "standard_portrait_pro_uncoated_paper": 51.0,
    "standard_portrait_standard_paper": 38.0
   },
   "imagewrap": {
    "large_format_landscape_premium_matte_layflat_paper": 117.0,
    "large_format_landscape_premium_paper": 78.0,
    "large_format_landscape_premium_paper_lustre": 78.0,
    "large_format_landscape_pro_medium_gloss_paper": 101.0,
    "large_format_landscape_pro_photo_layflat_paper": 159.0,
    "large_format_landscape_pro_uncoated_layflat_paper": 159.0,
    "large_format_landscape_pro_uncoated_paper": 91.0,
    "large_format_landscape_standard_layflat_paper": 120.0,
    "large_format_landscape_standard_paper": 70.0,
    "large_square_premium_matte_layflat_paper": 106.0,
    "large_square_premium_paper": 74.0,
    "large_square_premium_paper_lustre": 74.0,
    "large_square_pro_medium_gloss_paper": 95.0,
    "large_square_pro_photo_layflat_paper": 149.0,
    "large_square_pro_uncoated_layflat_paper": 149.0,
    "large_square_pro_uncoated_paper": 88.0,
    "large_square_standard_layflat_paper": 110.0,
    "large_square_standard_paper": 67.0,
    "square_premium_matte_layflat_paper": 58.0,
    "square_premium_paper": 37.0,
    "square_premium_paper_lustre": 37.0,
    "square_pro_medium_gloss_paper": 50.0,
    "square_pro_photo_layflat_paper": 89.0,
    "square_pro_uncoated_layflat_paper": 89.0,
    "square_pro_uncoated_paper": 46.0,
    "square_standard_layflat_paper": 60.0,
    "square_standard_paper": 32.0,
    "standard_landscape_premium_matte_layflat_paper": 68.0,
    "standard_landscape_premium_paper": 46.0,
    "standard_landscape_premium_paper_lustre": 46.0,
    "standard_landscape_pro_medium_gloss_paper": 60.0,
    "standard_landscape_pro_photo_layflat_paper": 109.0,
    "standard_landscape_pro_uncoated_layflat_paper": 109.0,
    "standard_landscape_pro_uncoated_paper": 53.0,
    "standard_landscape_standard_layflat_paper": 70.0,
    "standard_landscape_standard_paper": 41.0,
    "standard_portrait_premium_matte_layflat_paper": 68.0,
    "standard_portrait_premium_paper": 46.0,
    "standard_portrait_premium_paper_lustre": 46.0,
    "standard_portrait_pro_medium_gloss_paper": 60.0,
    "standard_portrait_pro_photo_layflat_paper": 109.0,
    "standard_portrait_pro_uncoated_layflat_paper": 109.0,
    "standard_portrait_pro_uncoated_paper": 53.0,
    "standard_portrait_standard_layflat_paper": 70.0,
    "standard_portrait_standard_paper": 41.0
   },
   "softcover": {
    "small_square_premium_paper_lustre": 12.0,
    "square_premium_paper": 22.0,
    "square_premium_paper_lustre": 22.0,
    "square_pro_medium_gloss_paper": 26.0,
    "square_pro_uncoated_paper": 25.0,
    "square_standard_paper": 17.0,
    "standard_landscape_premium_paper": 29.0,
    "standard_landscape_premium_paper_lustre": 29.0,
    "standard_landscape_pro_medium_gloss_paper": 37.0,
    "standard_landscape_pro_uncoated_paper": 32.0,
    "standard_landscape_standard_paper": 24.0,
    "standard_portrait_premium_paper": 29.0,
    "standard_portrait_premium_paper_lustre": 29.0,
    "standard_portrait_pro_medium_gloss_paper": 37.0,
    "standard_portrait_pro_uncoated_paper": 32.0,
    "standard_portrait_standard_paper": 24.0
   }
  },
  "trade_books": {
   "dustjacket": {
    "large_text_economy_trade_bw_matte_paper": 15.99,
    "large_text_economy_trade_matte_paper": 16.99,
    "large_text_standard_trade_bw_matte_paper": 18.99,
    "large_text_standard_trade_matte_paper": 21.99,
    "pocket_text_economy_trade_bw_matte_paper": 14.99,
    "pocket_text_economy_trade_matte_paper": 15.99,
    "pocket_text_standard_trade_matte_paper": 20.99
   },
   "imagewrap": {
    "large_text_economy_trade_bw_matte_paper": 13.99,
    "large_text_economy_trade_matte_paper": 14.99,
    "large_text_standard_trade_bw_matte_paper": 18.99,
    "large_text_standard_trade_matte_paper": 20.99,
    "pocket_text_economy_trade_bw_matte_paper": 12.99,
    "pocket_text_economy_trade_matte_paper": 13.99,
    "pocket_text_standard_trade_bw_matte_paper": 17.99,
    "pocket_text_standard_trade_matte_paper": 19.99,
    "standard_portrait_true8x10_economy_trade_matte_paper": 15.99,
    "standard_portrait_true8x10_standard_trade_bw_matte_paper": 19.99,
    "standard_portrait_true8x10_standard_trade_matte_paper": 22.99
   },
   "softcover": {
    "large_text_economy_trade_bw_matte_paper": 3.99,
    "large_text_economy_trade_matte_paper": 4.99,
    "large_text_standard_trade_bw_matte_paper": 5.99,
    "large_text_standard_trade_matte_paper": 7.99,
    "pocket_text_economy_trade_bw_matte_paper": 2.99,
    "pocket_text_economy_trade_matte_paper": 3.99,
    "pocket_text_standard_trade_bw_matte_paper": 4.99,
    "pocket_text_standard_trade_matte_paper": 6.99,
    "standard_portrait_true8x10_economy_trade_bw_matte_paper": 4.99,
    "standard_portrait_true8x10_economy_trade_matte_paper": 5.99,
    "standard_portrait_true8x10_standard_trade_bw_matte_paper": 6.99,
    "standard_portrait_true8x10_standard_trade_matte_paper": 8.99
   },
   "softcover_wireo": {
    "large_text_standard_trade_matte_paper": 7.99,
    "pocket_text_standard_trade_matte_paper": 6.99,
    "standard_portrait_true8x10_standard_trade_matte_paper": 8.99
   }
  }
 },
 "magazines": {
  "economy": 5.0,
  "premium": 7.0
 },
 "wallArt": {
  "metal_gloss": {
   "portrait_8x10": 65.0,
   "landscape_10x8": 65.0,
   "square_12x12": 89.0,
   "portrait_11x14": 89.0,
   "landscape_14x11": 89.0,
   "portrait_16x20": 129.0,
   "landscape_20x16": 129.0,
   "portrait_20x30": 209.0,
   "landscape_30x20": 209.0
  },
  "canvas_matte": {
   "portrait_8x10": 69.0,
   "landscape_10x8": 69.0,
   "square_12x12": 89.0,
   "portrait_11x14": 89.0,
   "landscape_14x11": 89.0,
   "portrait_16x20": 99.0,
   "landscape_20x16": 99.0,
   "portrait_20x24": 129.0,
   "landscape_24x20": 129.0,
   "portrait_20x30": 149.0,
   "landscape_30x20": 149.0
  },
  "acrylic_gloss": {
   "portrait_8x10": 79.0,
   "landscape_10x8": 79.0,
   "square_12x12": 109.0,
   "portrait_11x14": 109.0,
   "landscape_14x11": 109.0,
   "portrait_16x20": 139.0,
   "landscape_20x16": 139.0,
   "square_20x20": 189.0,
   "portrait_20x30": 229.0,
   "landscape_30x20": 229.0
  },
  "block_matte": {
   "portrait_8x10": 40.11,
   "landscape_10x8": 40.11,
   "square_12x12": 45.11,
   "portrait_11x14": 50.11,
   "landscape_14x11": 50.11,
   "portrait_16x20": 70.11,
   "landscape_20x16": 70.11,
   "portrait_20x30": 90.11,
   "landscape_30x20": 90.11
  },
  "poster_matte": {
   "portrait_8x10": 10.11,
   "landscape_10x8": 10.11,
   "square_12x12": 12.11,
   "portrait_11x14": 14.11,
   "landscape_14x11": 14.11,
   "portrait_16x20": 16.11,
   "landscape_20x16": 16.11,
   "square_20x20": 20.11,
   "portrait_20x24": 24.11,
   "landscape_24x20": 24.11,
   "portrait_20x30": 30.11,
   "landscape_30x20": 30.11
  }
 },
 "productOptions": {
  "pro_charcoal_linen_covering": 6.0,
  "pro_white_endsheet": 3.0
 }
};
